# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    container_name: chatbot_mariadb
#    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: chatbot_db
      MARIADB_USER: chatbot
      MARIADB_PASSWORD: chatbot
    ports:
      - "3306:3306"
    volumes:
      - volume:/var/lib/mysql

volumes:
    volume: